### PR TITLE
old api - node 15

### PR DESCRIPTION
**Pull request by k13-engineering**
Tested build on Node 8, 10, 12, 14 and 15.
Tests are running successfully.
I am actually using ntk, which works with this fix. I might have missed some errors.

### CODE REVIEW

**Comment by aminya** [comment]
@k13-engineering Could you rebase this?

**Comment by k13-engineering** [comment]
With the new changes the build is now working for Node 15. We can close this.

**Comment by aminya** [comment]
OK Thanks!

**Comment by aminya** [comment]
I decided to release this as 0.5 to allow people to use the old API.

**Pull request merged**
