### PR TITLE
fix for node 12

### LINKED ISSUE #11: Unable to build using nodejs v12
Having tried to clone the repository and build with nodeJs v12, I encountered the following issue that prevents the build to finish. 
Build is working fine with nodeJs v10.

`  CXX(target) Release/obj.target/freetype2/src/init.o
In file included from ../src/init.cc:1:0:
../src/FreeType2.h:10:26: error: ‘v8::Handle’ has not been declared
     static void Init(v8::Handle<v8::Object> exports);
                          ^~~~~~
../src/FreeType2.h:10:32: error: expected ‘,’ or ‘...’ before ‘<’ token
     static void Init(v8::Handle<v8::Object> exports);
                                ^
../src/init.cc: In function ‘void init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../src/init.cc:4:25: error: no matching function for call to ‘FreeType2::Init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE&)’
   FreeType2::Init(target);`

### PR DESCRIPTION
**Pull request by romgrk**
Closes #11

### CODE REVIEW

**Comment by ericfreese** [comment]
@Protryon

**Comment by aminya** [comment]
Any chance we can merge this? The current package does not work and it is not useful anymore.

**Comment by aminya** [comment]
There is a fork here https://github.com/julusian/node-freetype2 by @julusian. Could you help marging this?

**Comment by Julusian** [comment]
@aminya I am not expecting for my fork to be merged in, partly as this library does not appear to be maintained anymore, and due to the large scope of my changes.
I ended up pretty much completely rewriting the library while doing that, as I switched to the new native module api and needed to review all the existing code anyway as it was surprisingly easy to trigger a segfault.

The api should be mostly the same, but there are some differences and it is possible I didnt implement some bits yet too.
As a bonus, it shouldnt require much maintenance due to using the new native api, but I intend to look after it.

**Comment by aminya** [comment]
@Julusian We can first start by this pull request and then we can merge your fork.

**Comment by ericfreese** [comment]
@Protryon is the current maintainer of this package as of https://github.com/ericfreese/node-freetype2/pull/10#issuecomment-335049881. If he doesn't respond soon, would you be interested in taking over @aminya?

**Comment by aminya** [comment]
@ericfreese Sure! I will be happy to do so.

**Comment by aminya** [comment]
@ericfreese it seems that the previous maintainer is not active anymore

**Comment by Julusian** [comment]
I am happy to take over with my fork too

**Comment by aminya** [comment]
@ericfreese Could you give us access?

**Comment by ericfreese** [comment]
Ok @aminya i invited you as a collaborator. Let me know if you need anything else

**Comment by aminya** [comment]
Thank you! @ericfreese 

First of all, I will merge this! 🎉

**Pull request merged**
